---

- hosts: all
  become: true
  pre_tasks:

  - name: Create Users
    user:
      name: savila
      password: '$6$UsTmyff0ldY6ka$EgP4xto0.QrSKMum/wnsw/SDniFUkHvuv7LVkEkzmvH4xVRMJAYOe.IuUBkDC6HUbR2/hvehhQe8z44kN.TQs.'
      groups: 
        - sudo
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /home/savila
    when: ansible_distribution == "Ubuntu"


