---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and PHP package
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
        - tmux
        - vim-nox 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package
    dnf: 
      name: 
        - httpd
        - php 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

