---

- hosts: all
  become: true
  tasks:

  - name: update apk cache
    apt: 
      update_cache: yes

  - name: install apache package
    apt: 
      name: apache2

  - name: add php support
    apt: 
      name: libapache2-mod-php

  - name: add vim-nox
    apt: 
      name: vim-nox

  - name: add tmux
    apt: 
      name: tmux
