---

- hosts: all
  become: true
  tasks:

  - name: update apk cache
    apt: 
      update_cache: yes

  - name: install apache package
    apt: 
      name: apache2
      state: absent

  - name: add php support
    apt: 
      name: libapache2-mod-php
      state: absent

  - name: add vim-nox
    apt: 
      name: vim-nox
      state: latest

  - name: add tmux
    apt: 
      name: tmux
      state: latest
